# Data Describe
train_queries 500000 rows (not include head)

train_plans   491054 rows (not include head)

train_click   453336 rows (not include head)

train_merge 453336 rows (not include head)

test_queries 94358 rows (not include head)

test_plans 92571 rows (not include head)

test_merge 94358 rows (not include head)

# Initialize

In [10]:
import pandas as pd
import numpy as np
import os
from os import listdir
path = '/home/chiweilo/Desktop/Project/Second/rawData/'
path2 = '/home/chiweilo/Desktop/Project/Second/mergeData/'
if not os.path.exists(path2):
    os.makedirs(path2)

# Merge Trainning Raw Data

In [3]:
#Loading train_queries.csv Data
rawTrainQueriesData = pd.read_csv(path+'train_queries.csv',encoding = 'utf8')
#rawTrainQueriesData.replace('', np.nan, inplace=True)
rawTrainQueriesData['pid'].replace(np.nan, 0, inplace=True)
#rawTrainQueriesData.dropna(inplace=True)
rawTrainQueriesData.sort_values(by='sid',inplace=True)
rawTrainQueriesData.reset_index(drop=True, inplace=True)
print(rawTrainQueriesData.head())
print(rawTrainQueriesData.shape)

   sid       pid             req_time             o             d
0    2       0.0  2018-11-10 12:47:12  116.39,39.92  116.41,39.91
1   10  199899.0  2018-11-10 11:10:36  116.58,40.08  116.20,39.91
2   21  177401.0  2018-11-10 12:16:01  116.32,39.89  116.27,39.86
3   25  176887.0  2018-11-10 23:51:25  116.44,39.88  116.45,39.86
4   34       0.0  2018-11-10 13:42:54  116.29,40.07  116.44,39.93
(500000, 5)

In [4]:
#Loading train_plans.csv Data
rawTrainPlansData = pd.read_csv(path+'train_plans.csv',encoding = 'utf8')
#rawTrainPlansData.replace('', np.nan, inplace=True)
#rawTrainPlansData.dropna(inplace=True)
rawTrainPlansData.sort_values(by='sid',inplace=True)
rawTrainPlansData.reset_index(drop=True, inplace=True)
print(rawTrainPlansData.head())
print(rawTrainPlansData.shape)

   sid            plan_time                                              plans
0    2  2018-11-10 12:47:12  [{"distance": 2898, "price": 200, "eta": 1794,...
1   10  2018-11-10 11:10:36  [{"distance": 49067, "price": 3100, "eta": 634...
2   21  2018-11-10 12:16:01  [{"distance": 6157, "price": 300, "eta": 1289,...
3   25  2018-11-10 23:51:25  [{"distance": 3006, "price": 200, "eta": 2419,...
4   34  2018-11-10 13:42:54  [{"distance": 26039, "price": 600, "eta": 4411...
(491054, 3)

In [8]:
#Loading profiles.csv Data
rawProfilesData = pd.read_csv(path+'profiles.csv',encoding = 'utf8')
#rawProfilesData.replace('', np.nan, inplace=True)
#rawProfilesData.dropna(inplace=True)
pid0={'pid':0,
      'p0':0,'p1':0,'p2':0,'p3':0,'p4':0,'p5':0,'p6':0,'p7':0,'p8':0,'p9':0,
      'p10':0,'p11':0,'p12':0,'p13':0,'p14':0,'p15':0,'p16':0,'p17':0,'p18':0,'p19':0,
      'p20':0,'p21':0,'p22':0,'p23':0,'p24':0,'p25':0,'p26':0,'p27':0,'p28':0,'p29':0,
      'p30':0,'p31':0,'p32':0,'p33':0,'p34':0,'p35':0,'p36':0,'p37':0,'p38':0,'p39':0,
      'p40':0,'p41':0,'p42':0,'p43':0,'p44':0,'p45':0,'p46':0,'p47':0,'p48':0,'p49':0,
      'p50':0,'p51':0,'p52':0,'p53':0,'p54':0,'p55':0,'p56':0,'p57':0,'p58':0,'p59':0,
      'p60':0,'p61':0,'p62':0,'p63':0,'p64':0,'p65':0,
     }
rawProfilesData = rawProfilesData.append(pid0,ignore_index=True)
rawProfilesData.sort_values(by='pid',inplace=True)
rawProfilesData.reset_index(drop=True, inplace=True)
print(rawProfilesData.head())
print(rawProfilesData.shape)

      pid   p0   p1   p2   p3   p4   p5   p6   p7   p8 ...   p56  p57  p58  \
0       0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0
1  100000  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0 ...   0.0  0.0  0.0
2  100002  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0 ...   0.0  0.0  0.0
3  100004  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0 ...   0.0  0.0  0.0
4  100005  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0 ...   0.0  0.0  0.0

   p59  p60  p61  p62  p63  p64  p65
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0  0.0  0.0
2  0.0  1.0  0.0  0.0  0.0  0.0  0.0
3  0.0  1.0  0.0  0.0  0.0  0.0  0.0
4  0.0  1.0  0.0  0.0  0.0  0.0  0.0

[5 rows x 67 columns]
(63091, 67)

In [6]:
#Loading train_clicks.csv Data
rawTrainClicksData = pd.read_csv(path+'train_clicks.csv',encoding = 'utf8')
#rawTrainClicksData.replace('', np.nan, inplace=True)
#rawTrainClicksData.dropna(inplace=True)
rawTrainClicksData.sort_values(by='sid',inplace=True)
rawTrainClicksData.reset_index(drop=True, inplace=True)
print(rawTrainClicksData.head())
print(rawTrainClicksData.shape)

   sid           click_time  click_mode
0   10  2018-11-10 11:13:24           1
1   21  2018-11-10 12:16:36           2
2   25  2018-11-10 23:51:30           1
3   34  2018-11-10 13:43:19           9
4   35  2018-11-10 16:37:25           1
(453336, 3)

In [7]:
#Merge rawTrainData
rawTrainMergeData = rawTrainQueriesData.merge(rawTrainPlansData,left_on='sid',right_on='sid')
rawTrainMergeData = rawTrainMergeData.merge(rawProfilesData,left_on='pid',right_on='pid')
rawTrainMergeData = rawTrainMergeData.merge(rawTrainClicksData,left_on='sid',right_on='sid')
rawTrainMergeData.sort_values(by='sid',inplace=True)
rawTrainMergeData.reset_index(drop=True, inplace=True)
print(rawTrainMergeData.head())
print(rawTrainMergeData.shape)

   sid       pid             req_time             o             d  \
0   10  199899.0  2018-11-10 11:10:36  116.58,40.08  116.20,39.91
1   21  177401.0  2018-11-10 12:16:01  116.32,39.89  116.27,39.86
2   25  176887.0  2018-11-10 23:51:25  116.44,39.88  116.45,39.86
3   34       0.0  2018-11-10 13:42:54  116.29,40.07  116.44,39.93
4   35  106441.0  2018-11-10 16:37:17  116.17,39.92  116.20,39.93

             plan_time                                              plans  \
0  2018-11-10 11:10:36  [{"distance": 49067, "price": 3100, "eta": 634...
1  2018-11-10 12:16:01  [{"distance": 6157, "price": 300, "eta": 1289,...
2  2018-11-10 23:51:25  [{"distance": 3006, "price": 200, "eta": 2419,...
3  2018-11-10 13:42:54  [{"distance": 26039, "price": 600, "eta": 4411...
4  2018-11-10 16:37:17  [{"distance": 4415, "price": 200, "eta": 2050,...

    p0   p1   p2     ...      p58  p59  p60  p61  p62  p63  p64  p65  \
0  1.0  0.0  0.0     ...      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
1  0.0  0.0  0.0     ...      0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0
2  0.0  0.0  1.0     ...      0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0
3  0.0  0.0  0.0     ...      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
4  1.0  0.0  0.0     ...      0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0

            click_time  click_mode
0  2018-11-10 11:13:24           1
1  2018-11-10 12:16:36           2
2  2018-11-10 23:51:30           1
3  2018-11-10 13:43:19           9
4  2018-11-10 16:37:25           1

[5 rows x 75 columns]
(453336, 75)

In [8]:
rawTrainMergeData.to_csv(path2+'train_merges.csv',index=False)

# Merge Testing Raw Data

In [15]:
#Loading test_queries.csv Data
rawTestQueriesData = pd.read_csv(path+'test_queries.csv',encoding = 'utf8')
#rawTestQueriesData.replace('', np.nan, inplace=True)
rawTestQueriesData['pid'].replace(np.nan, 0, inplace=True)
#rawTestQueriesData.dropna(inplace=True)
rawTestQueriesData.sort_values(by='sid',inplace=True)
rawTestQueriesData.reset_index(drop=True, inplace=True)
print(rawTestQueriesData.head())
print(rawTestQueriesData.shape)

      sid       pid             req_time             o             d
0  420123       0.0  2018-12-01 18:31:03  116.28,39.91  116.40,40.00
1  420125       0.0  2018-12-01 21:43:33  116.40,40.00  116.27,39.92
2  420127       0.0  2018-12-01 18:28:23  116.28,39.91  116.40,40.00
3  420129       0.0  2018-12-01 18:37:44  116.28,39.92  116.40,40.00
4  420134  114321.0  2018-12-01 18:01:41  116.46,39.56  116.44,39.56
(94358, 5)

In [16]:
#Loading test_plans.csv Data
rawTestPlansData = pd.read_csv(path+'test_plans.csv',encoding = 'utf8')
#rawTestPlansData.replace('', np.nan, inplace=True)
#rawTestPlansData.dropna(inplace=True)
rawTestPlansData.sort_values(by='sid',inplace=True)
rawTestPlansData.reset_index(drop=True, inplace=True)
print(rawTestPlansData.head())
print(rawTestPlansData.shape)

      sid            plan_time  \
0  420123  2018-12-01 18:31:03
1  420125  2018-12-01 21:43:33
2  420127  2018-12-01 18:28:23
3  420129  2018-12-01 18:37:44
4  420134  2018-12-01 18:01:41

                                               plans
0  [{"distance": 22691, "price": 700, "eta": 4888...
1  [{"distance": 20310, "price": "", "eta": 1484,...
2  [{"distance": 22706, "price": 700, "eta": 4883...
3  [{"distance": 22378, "price": 700, "eta": 4594...
4  [{"distance": 1148, "price": "", "eta": 125, "...
(92571, 3)

In [17]:
#Merge rawTestData
rawTestMergeData = rawTestQueriesData.merge(rawTestPlansData,left_on='sid',right_on='sid',how='outer')
rawTestMergeData = rawTestMergeData.merge(rawProfilesData,left_on='pid',right_on='pid')
rawTestMergeData.sort_values(by='sid',inplace=True)
rawTestMergeData.reset_index(drop=True, inplace=True)
print(rawTestMergeData.head())
print(rawTestMergeData.shape)
rawTestMergeData.replace(np.nan, 'empty', inplace=True)

      sid       pid             req_time             o             d  \
0  420123       0.0  2018-12-01 18:31:03  116.28,39.91  116.40,40.00
1  420125       0.0  2018-12-01 21:43:33  116.40,40.00  116.27,39.92
2  420127       0.0  2018-12-01 18:28:23  116.28,39.91  116.40,40.00
3  420129       0.0  2018-12-01 18:37:44  116.28,39.92  116.40,40.00
4  420134  114321.0  2018-12-01 18:01:41  116.46,39.56  116.44,39.56

             plan_time                                              plans  \
0  2018-12-01 18:31:03  [{"distance": 22691, "price": 700, "eta": 4888...
1  2018-12-01 21:43:33  [{"distance": 20310, "price": "", "eta": 1484,...
2  2018-12-01 18:28:23  [{"distance": 22706, "price": 700, "eta": 4883...
3  2018-12-01 18:37:44  [{"distance": 22378, "price": 700, "eta": 4594...
4  2018-12-01 18:01:41  [{"distance": 1148, "price": "", "eta": 125, "...

    p0   p1   p2 ...   p56  p57  p58  p59  p60  p61  p62  p63  p64  p65
0  0.0  0.0  0.0 ...   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
1  0.0  0.0  0.0 ...   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
2  0.0  0.0  0.0 ...   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
3  0.0  0.0  0.0 ...   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
4  0.0  0.0  0.0 ...   0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0

[5 rows x 73 columns]
(94358, 73)

In [18]:
rawTestMergeData.to_csv(path2+'test_merges.csv',index=False)

In [21]:
rawTestMergeData[rawTestMergeData['plans']=='empty']

,sid,pid,req_time,o,d,plan_time,plans,p0,p1,p2,...,p56,p57,p58,p59,p60,p61,p62,p63,p64,p65
54,420307,0.0,2018-12-01 12:33:32,"117.02,40.14","116.37,39.91",empty,empty,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
85,420399,0.0,2018-12-01 10:26:07,"116.55,39.91","116.45,39.88",empty,empty,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
166,420556,0.0,2018-12-01 07:08:47,"116.45,39.80","116.42,39.74",empty,empty,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
340,421065,0.0,2018-12-01 18:21:34,"116.32,39.89","116.45,39.93",empty,empty,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
453,421368,195199.0,2018-12-01 20:27:24,"116.39,39.79","116.40,39.91",empty,empty,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
514,421518,0.0,2018-12-01 13:39:20,"116.36,39.94","116.45,39.93",empty,empty,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
537,421586,124124.0,2018-12-01 13:30:28,"116.23,39.95","116.33,39.96",empty,empty,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
542,421594,0.0,2018-12-01 22:22:30,"116.50,39.87","116.51,39.90",empty,empty,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
593,421725,186452.0,2018-12-01 23:48:56,"116.33,39.96","116.34,39.98",empty,empty,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
664,421856,110567.0,2018-12-01 05:05:42,"116.42,39.90","116.47,39.86",empty,empty,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
718,421989,170713.0,2018-12-01 10:44:21,"116.37,39.90","116.42,39.90",empty,empty,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1002,422677,167206.0,2018-12-01 22:48:27,"116.32,39.89","116.26,40.02",empty,empty,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1319,423546,189660.0,2018-12-01 19:52:50,"116.32,39.89","116.36,39.99",empty,empty,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1324,423559,195920.0,2018-12-01 21:18:44,"116.55,39.91","116.60,39.71",empty,empty,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1376,423687,131381.0,2018-12-01 16:06:20,"115.83,39.48","115.78,39.49",empty,empty,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1501,424036,150961.0,2018-12-01 11:42:46,"116.32,39.89","116.65,40.13",empty,empty,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1539,424134,0.0,2018-12-01 19:53:56,"116.34,39.95","116.31,39.84",empty,empty,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1575,424277,0.0,2018-12-01 21:04:27,"116.39,39.78","116.37,39.86",empty,empty,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1576,424292,0.0,2018-12-01 01:13:19,"116.39,39.78","116.37,39.86",empty,empty,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1577,424293,0.0,2018-12-01 20:52:21,"116.39,39.78","116.37,39.86",empty,empty,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1578,424317,0.0,2018-12-01 04:40:19,"116.39,39.78","116.37,39.86",empty,empty,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1579,424343,0.0,2018-12-01 08:49:23,"116.39,39.78","116.37,39.86",empty,empty,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1580,424384,0.0,2018-12-01 15:37:21,"116.39,39.78","116.37,39.86",empty,empty,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1581,424460,0.0,2018-12-01 08:13:20,"116.39,39.78","116.37,39.86",empty,empty,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1582,424480,0.0,2018-12-01 16:25:21,"116.39,39.78","116.37,39.86",empty,empty,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1583,424483,0.0,2018-12-01 06:34:17,"116.39,39.78","116.37,39.86",empty,empty,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1584,424492,0.0,2018-12-01 07:34:20,"116.39,39.78","116.37,39.86",empty,empty,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1585,424503,0.0,2018-12-01 05:04:29,"116.39,39.78","116.37,39.86",empty,empty,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1586,424522,0.0,2018-12-01 17:49:21,"116.39,39.78","116.37,39.86",empty,empty,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1587,424581,0.0,2018-12-01 21:40:20,"116.39,39.78","116.37,39.86",empty,empty,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93373,2075787,202643.0,2018-12-07 12:23:30,"116.28,40.15","116.26,40.15",empty,empty,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
93413,2076010,0.0,2018-12-07 16:44:02,"116.33,39.89","116.36,39.95",empty,empty,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
93468,2076286,200066.0,2018-12-07 23:02:58,"116.42,39.90","116.38,39.88",empty,empty,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
93503,2076528,172334.0,2018-12-07 13:13:39,"116.47,39.91","116.52,39.92",empty,empty,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
93581,2076978,0.0,2018-12-07 12:48:14,"116.56,39.78","116.42,39.90",empty,empty,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
93658,2077331,127774.0,2018-12-07 19:29:46,"116.56,40.11","116.61,40.13",empty,empty,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
93669,2077395,197702.0,2018-12-07 17:27:09,"116.68,39.90","116.68,39.89",empty,empty,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
93714,2077694,0.0,2018-12-07 16:50:12,"116.43,39.94","116.64,40.32",empty,empty,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
93722,2077798,138283.0,2018-12-07 10:36:45,"116.13,39.86","116.51,39.92",empty,empty,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
93745,2077945,107109.0,2018-12-07 19:01:48,"116.42,39.90","116.66,39.65",empty,empty,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
93754,2077996,215140.0,2018-12-07 23:34:06,"116.16,40.07","116.46,40.01",empty,empty,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
93758,2078029,203016.0,2018-12-07 20:14:55,"116.59,40.08","116.54,39.91",empty,empty,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
93766,2078071,198512.0,2018-12-07 23:53:25,"116.39,39.79","116.32,39.89",empty,empty,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
93772,2078095,0.0,2018-12-07 10:55:37,"116.42,39.93","116.34,39.79",empty,empty,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
93798,2078234,167770.0,2018-12-07 17:30:59,"116.37,39.86","116.51,39.93",empty,empty,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
93838,2078448,141409.0,2018-12-07 00:12:48,"116.30,40.05","116.30,40.05",empty,empty,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
93856,2078570,0.0,2018-12-07 08:26:58,"116.35,40.01","116.44,39.92",empty,empty,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
93917,2078793,0.0,2018-12-07 20:15:40,"116.39,39.79","116.44,39.95",empty,empty,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
93927,2078849,202500.0,2018-12-07 22:15:36,"116.46,39.93","116.53,39.92",empty,empty,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
93940,2078904,131986.0,2018-12-07 20:04:39,"116.32,39.89","115.96,39.72",empty,empty,0.0,0.0,1.0,...,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
93993,2079243,189067.0,2018-12-07 15:25:51,"116.64,40.13","116.41,39.86",empty,empty,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
94001,2079307,101600.0,2018-12-07 12:13:01,"116.37,39.85","116.42,39.71",empty,empty,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
94164,2080227,194438.0,2018-12-07 18:42:45,"116.39,39.79","116.55,39.90",empty,empty,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
94169,2080244,104897.0,2018-12-07 16:34:16,"116.33,39.72","116.44,39.95",empty,empty,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
94201,2080406,112198.0,2018-12-07 12:57:10,"116.32,39.89","116.42,39.90",empty,empty,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
94206,2080435,181962.0,2018-12-07 10:46:42,"116.30,39.97","116.43,39.98",empty,empty,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
94227,2080566,106256.0,2018-12-07 18:32:09,"116.29,40.15","116.37,39.92",empty,empty,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
94231,2080596,120327.0,2018-12-07 09:28:01,"116.46,39.90","116.43,39.85",empty,empty,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
94254,2080691,109954.0,2018-12-07 06:41:06,"116.25,39.90","116.21,39.90",empty,empty,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
94349,2081123,188988.0,2018-12-07 08:49:41,"116.58,40.13","116.41,39.73",empty,empty,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0